### ISSUE TITLE
Problems in typings

### ISSUE THREAD

**Issue by ksnyde** [gajus/table#151] opened 2021-04-19 19:23 UTC
<img width="890" alt="2021-04-19_12-22-14" src="https://user-images.githubusercontent.com/980757/115291786-01fc7800-a10a-11eb-8a5a-eeab440b32bf.png">

Upgraded to `6.3.0` and can no longer build using Typescripts `tsc` compiler due to upstream issues in **Table**.  When publishing library code I would strongly suggest using the strictest setting in Typescript (not sure if that's what the issue is but I suspect that's why you didn't see it).

It's possible -- but unlikely -- that this issue is on my end. I will roll back to prior release for now.

**Comment by ksnyde** [comment] 2021-04-19 19:24
ping me if you want to pair on this

**Comment by gajus** [comment] 2021-04-19 22:05
@nam-hle

**Comment by nam-hle** [comment] 2021-04-20 03:50
> <img alt="2021-04-19_12-22-14" width="890" src="https://user-images.githubusercontent.com/980757/115291786-01fc7800-a10a-11eb-8a5a-eeab440b32bf.png">
> 
> Upgraded to `6.3.0` and can no longer build using Typescripts `tsc` compiler due to upstream issues in **Table**. When publishing library code I would strongly suggest using the strictest setting in Typescript (not sure if that's what the issue is but I suspect that's why you didn't see it).
> 
> It's possible -- but unlikely -- that this issue is on my end. I will roll back to prior release for now.

Hi @ksnyde, the problem is not about strict mode, I turned on all strict settings. It’s from I did not turn on lib check (skipLibCheck) when testing in the user land. I also fixed it in #153. 

Cheers.

**Comment by nam-hle** [comment] 2021-05-02 07:55
This issue is fixed in #153. Please close this.

**Comment by ksnyde** [comment] 2021-05-03 15:07
Thanks for doing this. My _table_-based life has improved already. :)

**Closed** 2021-05-03 15:06 UTC
Labels: bug
